# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 549891cc63f9dbdec5f3da0f84e1e4adcc8fac4b5398cee16f23707cf217541686513af006d64ef63f66f6eac9e45168f290f44701b9e5d69a8327a2a554e83b

test:
  secret_key_base: d500fd15e39ef3fd297e01d8e0088c694db38062eeb7c6cac0350a36098c075dc069341651efaaa0d57805c14fefc4aa41277deea03537fa87156c787cefbaeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
